<div class="jumbotron">
    <h1>Welcome to <span class="zf-green">Zend Framework Inicial Project</span></h1>

    <p>
        My name is  <span class="zf-green">Pedro Augusto!</span> Thank you for knowing my first project with zend framework. I'm happy and I hope you like what you find
    </p>

    <p><a class="btn btn-success btn-lg" href="https://github.com/pedro749" target="_blank">Acess my github &raquo;</a></p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title">See my Portfolio</h2>
            </div>
            <div class="card-body">
                <p>
                I'm a fullstack programmer with over two years of experience, check out my online portfolio to see things I've produced.
                </p>

                <p><a class="btn btn-success pull-right" href="https://my-portifolio-opal.vercel.app/" target="_blank">Acessar &raquo;</a></p>
            </div>
        </div>
    </div>

</div>
